<a href="https://colab.research.google.com/github/alikaiser12/AI/blob/main/E-book-AI-with-zero-knowledge-Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# এই সেল রান করুন, তারপর sales_week1.csv নির্বাচন করুন
from google.colab import files
uploaded = files.upload()


import pandas as pd
import io
# আপলোড করা প্রথম ফাইলটি পড়া
df = pd.read_csv(io.BytesIO(uploaded[list(uploaded.keys())[0]]))
# প্রথম ৫টি সারি দেখা
df.head()

Saving sales_week1.csv to sales_week1.csv


date      store  amount
0  2024-09-01  Dhanmondi   12500
1  2024-09-02     Uttara    9800
2  2024-09-03    Gulshan   17100
3  2024-09-04     Mirpur   11250
4  2024-09-05  Motijheel   15450

In [ ]:
# Drive কানেক্ট
from google.colab import drive
drive.mount('/content/drive')


import pandas as pd
path = '/content/drive/MyDrive/Ai with Zero Knowledge/sales_week1.csv'
# ফাইল পড়া
pd.read_csv(path).head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


date      store  amount
0  2024-09-01  Dhanmondi   12500
1  2024-09-02     Uttara    9800
2  2024-09-03    Gulshan   17100
3  2024-09-04     Mirpur   11250
4  2024-09-05  Motijheel   15450

In [ ]:
# এই সেল রান করুন, তারপর sales_week1.csv নির্বাচন করুন
from google.colab import files
uploaded = files.upload()


import pandas as pd
import io
# আপলোড করা প্রথম ফাইলটি পড়া
df = pd.read_csv(io.BytesIO(uploaded[list(uploaded.keys())[0]]))
# প্রথম ৫টি সারি দেখা
df.head()

Saving sales_week2.csv to sales_week2.csv


date      store  amount
0  2024-09-06  Dhanmondi   16200
1  2024-09-07     Uttara   10100
2  2024-09-08    Gulshan   18350
3  2024-09-09     Mirpur   12900
4  2024-09-10  Motijheel   16820

In [ ]:
import pandas as pd


week1 = pd.read_csv('sales_week1.csv') # সপ্তাহ ১ এর বিক্রি
week2 = pd.read_csv('sales_week2.csv') # সপ্তাহ ২ এর বিক্রি


# দুই সপ্তাহকে একসাথে জোড়া
sales = pd.concat([week1, week2], ignore_index=True)


# দোকানভিত্তিক সারাংশ: কতটি ট্রানজ্যাকশন (count), মোট (sum), গড় (mean)
summary = (sales
.groupby('store')['amount']
.agg(['count','sum','mean'])
.reset_index())


# ফলাফল দেখা
summary


# রিপোর্ট ফাইলে সংরক্ষণ
summary.to_csv('sales_summary.csv', index=False)

In [ ]:
# নাম, বয়স, স্কোর সংরক্ষণ
name = "Rafi"
age = 15
score = 85

print(name)
print(age)
print(score)


Rafi
15
85


In [ ]:
city = "Dhaka"
population = 12000000
temperature = 29.5
rainy = False

print(type(city))
print(type(population))


<class 'str'>
<class 'int'>


In [ ]:
marks = 72

if marks >= 80:
    print("A+")
elif marks >= 60:
    print("B")
else:
    print("Try again!")


B


In [ ]:
# ১ থেকে ৫ পর্যন্ত সংখ্যা প্রিন্ট করা
for i in range(1, 6):
    print("Number:", i)


Number: 1
Number: 2
Number: 3
Number: 4
Number: 5


In [ ]:
def add_numbers(a, b):
    result = a + b
    return result

print(add_numbers(5, 3))


8


In [ ]:
# পণ্য ও দাম
product = ["Pen", "Pencil", "Notebook", "Eraser"]
price = [10, 5, 30, 8]
quantity = [5, 10, 3, 4]

# মোট বিক্রি হিসাব
total = 0
for i in range(len(product)):
    total += price[i] * quantity[i]

print("মোট বিক্রি:", total, "টাকা")


মোট বিক্রি: 222 টাকা


In [ ]:
import pandas as pd

# ফাইল পড়া
data = pd.read_csv("sales_week1.csv")

# প্রথম ৫টি সারি দেখা
print(data.head())


         date      store  amount
0  2024-09-01  Dhanmondi   12500
1  2024-09-02     Uttara    9800
2  2024-09-03    Gulshan   17100
3  2024-09-04     Mirpur   11250
4  2024-09-05  Motijheel   15450


In [ ]:
import pandas as pd

excel_data = pd.read_excel("/content/drive/MyDrive/Ai with Zero Knowledge/student_marks.xlsx")
print(excel_data.head())


   student_id    name  math  english  science  total  average
0         101    Anik    78       82       80    240    80.00
1         102    Riya    85       74       79    238    79.33
2         103   Sadia    90       88       91    269    89.67
3         104   Mahin    65       69       72    206    68.67
4         105  Nusrat    88       92       85    265    88.33


In [ ]:
import pandas as pd

week1 = pd.read_csv("sales_week1.csv")
week2 = pd.read_csv("sales_week2.csv")

# একত্র করা
merged = pd.concat([week1, week2])

print(merged.head())


         date      store  amount
0  2024-09-01  Dhanmondi   12500
1  2024-09-02     Uttara    9800
2  2024-09-03    Gulshan   17100
3  2024-09-04     Mirpur   11250
4  2024-09-05  Motijheel   15450


In [ ]:
students = pd.read_csv("/content/drive/MyDrive/Ai with Zero Knowledge/students.csv")
marks = pd.read_csv("/content/drive/MyDrive/Ai with Zero Knowledge/marks.csv")

# Student ID দিয়ে যুক্ত করা
combined = pd.merge(students, marks, on="student_id")

print(combined.head())


   student_id    name        dept  cgpa  math  english  science
0         101    Anik         CSE  3.70    78       82       80
1         102    Riya         BBA  3.10    85       74       79
2         103   Sadia     English  3.40    90       88       91
3         104   Mahin         EEE  2.95    65       69       72
4         105  Farhan  Statistics  3.85    88       92       85


In [ ]:
combined.to_csv("final_report.csv", index=False)


In [ ]:
import pandas as pd

# দুই সপ্তাহের ফাইল পড়া
week1 = pd.read_csv("sales_week1.csv")
week2 = pd.read_csv("sales_week2.csv")

# একত্র করা
sales = pd.concat([week1, week2])

# দোকানভিত্তিক সারাংশ
summary = sales.groupby("store")["amount"].agg(["count", "sum", "mean"]).reset_index()

# সংরক্ষণ
summary.to_csv("sales_summary.csv", index=False)

print(summary)


       store  count    sum     mean
0  Dhanmondi      2  28700  14350.0
1    Gulshan      2  35450  17725.0
2     Mirpur      2  24150  12075.0
3  Motijheel      2  32270  16135.0
4     Uttara      2  19900   9950.0


In [ ]:
!pip install numpy


In [ ]:
import numpy as np


In [ ]:
import numpy as np

# একটি সাধারণ লিস্টকে অ্যারে বানানো
numbers = np.array([10, 20, 30, 40, 50])

print(numbers)
print("মোট উপাদান সংখ্যা:", numbers.size)
print("আকার (shape):", numbers.shape)


[10 20 30 40 50]
মোট উপাদান সংখ্যা: 5
আকার (shape): (5,)


In [ ]:
import numpy as np

a = np.array([5, 10, 15])
b = np.array([2, 4, 6])

print(a + b)   # যোগ
print(a - b)   # বিয়োগ
print(a * b)   # গুণ
print(a / b)   # ভাগ


[ 7 14 21]
[3 6 9]
[10 40 90]
[2.5 2.5 2.5]


In [ ]:
data = np.array([10, 20, 30, 40, 50])

print("মোট:", np.sum(data))
print("গড়:", np.mean(data))
print("সর্বনিম্ন:", np.min(data))
print("সর্বোচ্চ:", np.max(data))
print("স্ট্যান্ডার্ড ডিভিয়েশন:", np.std(data))


মোট: 150
গড়: 30.0
সর্বনিম্ন: 10
সর্বোচ্চ: 50
স্ট্যান্ডার্ড ডিভিয়েশন: 14.142135623730951


In [ ]:
import numpy as np

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(matrix)
print("দ্বিতীয় সারি:", matrix[1])
print("প্রথম কলাম:", matrix[:, 0])


[[10 20 30]
 [40 50 60]
 [70 80 90]]
দ্বিতীয় সারি: [40 50 60]
প্রথম কলাম: [10 40 70]


In [ ]:
import numpy as np

# ছাত্রদের নামের সাথে মার্কস
marks = np.array([
    [78, 82, 80],  # Anik
    [85, 74, 79],  # Riya
    [90, 88, 91],  # Sadia
    [65, 69, 72],  # Mahin
    [88, 92, 85]   # Nusrat
])

# প্রতিটি ছাত্রের গড়
avg_marks = np.mean(marks, axis=1)
print("প্রতিটি ছাত্রের গড় নম্বর:", avg_marks)

# পুরো ক্লাসের গড়
class_avg = np.mean(marks)
print("পুরো ক্লাসের গড়:", class_avg)


প্রতিটি ছাত্রের গড় নম্বর: [80.         79.33333333 89.66666667 68.66666667 88.33333333]
পুরো ক্লাসের গড়: 81.2


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[0:3])   # প্রথম ৩টি উপাদান
print(arr[2:])    # ২ নম্বর ইন্ডেক্স থেকে শেষ পর্যন্ত
print(arr[-3:])   # শেষের ৩টি উপাদান


[10 20 30]
[30 40 50 60]
[40 50 60]


বাংলা ব্যাখ্যা:

arr[0:3] মানে ইন্ডেক্স ০ থেকে ২ পর্যন্ত মান।

arr[-3:] মানে পেছন থেকে ৩টা মান।

এই slicing Excel-এর “Filter” এর মতোই ডেটা বাছাই করার উপায়।

In [ ]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(matrix[0:2, 1:3])   # প্রথম ২ সারি, কলাম ১ ও ২
print(matrix[:, 0])       # সব সারির প্রথম কলাম
print(matrix[1, :])       # দ্বিতীয় সারি সম্পূর্ণ


[[20 30]
 [50 60]]
[10 40 70]
[40 50 60]


বাংলা ব্যাখ্যা:

: মানে “সব”,

[0:2, 1:3] মানে সারি ০–১ আর কলাম ১–২।

এটা টেবিলের নির্দিষ্ট অংশ কেটে নেওয়ার মতো।

In [ ]:
arr = np.array([10, 20, 30])
print(arr + 5)    # প্রতিটির সাথে ৫ যোগ
print(arr * 2)    # প্রতিটির সাথে ২ গুণ


[15 25 35]
[20 40 60]


বাংলা ব্যাখ্যা:

প্রতিটি মানের সাথে স্বয়ংক্রিয়ভাবে কাজ করে।

Excel-এ যেভাবে একটি সেলে ফর্মুলা কপি করো, NumPy সেটা নিজে থেকেই করে ফেলে।

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)


[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

# প্রতিটি ছাত্রের তিনটি বিষয়ের মার্কস (মোট ৬ ছাত্র × ৩ বিষয়)
marks = np.array([78, 82, 80, 85, 74, 79, 90, 88, 91, 65, 69, 72, 88, 92, 85, 77, 81, 79])

reshaped = marks.reshape(6, 3)
print("আকার:", reshaped.shape)
print(reshaped)


আকার: (6, 3)
[[78 82 80]
 [85 74 79]
 [90 88 91]
 [65 69 72]
 [88 92 85]
 [77 81 79]]


In [ ]:
import numpy as np

sales = np.array([100,120,130,110,115,150,160,140,155,170,180,175])
reshaped = sales.reshape(4,3)  # ৪ সপ্তাহ × ৩ দিন
print(reshaped)

weekly_avg = np.mean(reshaped, axis=1)
print("সাপ্তাহিক গড় বিক্রি:", weekly_avg)


[[100 120 130]
 [110 115 150]
 [160 140 155]
 [170 180 175]]
সাপ্তাহিক গড় বিক্রি: [116.66666667 125.         151.66666667 175.        ]


In [ ]:
!pip install pandas


In [ ]:
import pandas as pd


In [ ]:
import pandas as pd

data = pd.read_csv("sales_week1.csv")

print(data.head())   # প্রথম ৫টি সারি দেখায়


         date      store  amount
0  2024-09-01  Dhanmondi   12500
1  2024-09-02     Uttara    9800
2  2024-09-03    Gulshan   17100
3  2024-09-04     Mirpur   11250
4  2024-09-05  Motijheel   15450


In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Rafi", "Sadia", "Nusrat"],
    "Age": [15, 16, 15],
    "Score": [80, 90, 88]
})

print(df)


     Name  Age  Score
0    Rafi   15     80
1   Sadia   16     90
2  Nusrat   15     88


In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Rafi", "Sadia", "Nusrat"],
    "Age": [15, 16, 15],
    "Score": [80, 90, 88]
})

print(df)


     Name  Age  Score
0    Rafi   15     80
1   Sadia   16     90
2  Nusrat   15     88


In [ ]:
print(df["Name"])        # একটি কলাম
print(df[["Name","Score"]])   # একাধিক কলাম

print(df.iloc[0])        # প্রথম সারি
print(df.iloc[1:3])      # ২য় থেকে ৩য় সারি


0      Rafi
1     Sadia
2    Nusrat
Name: Name, dtype: object
     Name  Score
0    Rafi     80
1   Sadia     90
2  Nusrat     88
Name     Rafi
Age        15
Score      80
Name: 0, dtype: object
     Name  Age  Score
1   Sadia   16     90
2  Nusrat   15     88


In [ ]:
high_score = df[df["Score"] > 85]
print(high_score)


     Name  Age  Score
1   Sadia   16     90
2  Nusrat   15     88


In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Ai with Zero Knowledge/sales_data.csv")

# খালি মান চেক
print(data.isnull().sum())

# খালি মান পূরণ
data["amount"] = data["amount"].fillna(0)


date        0
store       0
amount      2
category    0
dtype: int64


In [ ]:
data = data.drop_duplicates()


In [ ]:
sorted_data = data.sort_values(by="amount", ascending=False)
print(sorted_data)


         date      store   amount     category
7  2024-09-08    Gulshan  18350.0      Clothes
2  2024-09-03    Gulshan  17100.0  Electronics
5  2024-09-06  Dhanmondi  16200.0  Electronics
4  2024-09-05  Motijheel  15450.0         Food
8  2024-09-09     Mirpur  12900.0         Food
0  2024-09-01  Dhanmondi  12500.0   Stationary
6  2024-09-07     Uttara  10100.0   Stationary
1  2024-09-02     Uttara   9800.0         Food
3  2024-09-04     Mirpur      0.0      Clothes
9  2024-09-10  Motijheel      0.0  Electronics


In [ ]:
import pandas as pd

df = pd.read_csv("sales_week1.csv")

# খালি মান পূরণ
df["amount"] = df["amount"].fillna(0)

# ডুপ্লিকেট বাদ
df = df.drop_duplicates()

# দোকানভিত্তিক রিপোর্ট
report = df.groupby("store")["amount"].agg(["count","sum","mean"]).reset_index()

print(report)
report.to_csv("clean_sales_report.csv", index=False)


       store  count    sum     mean
0  Dhanmondi      1  12500  12500.0
1    Gulshan      1  17100  17100.0
2     Mirpur      1  11250  11250.0
3  Motijheel      1  15450  15450.0
4     Uttara      1   9800   9800.0
