<a href="https://colab.research.google.com/github/alikaiser12/AI/blob/main/python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Variable Types

In [ ]:
# Integer
x = 5
print("Integer:", x)

# Float
pi = 3.14
print("Float:", pi)

# String
name = "Alice"
print("String:", name)

# Boolean
is_sunny = True
print("Boolean:", is_sunny)

# Type Checking
print("Type of x:", type(x))

Integer: 5
Float: 3.14
String: Alice
Boolean: True
Type of x: <class 'int'>


In [ ]:
# Integer
x = 500
print("Integer:", x)

Integer: 500


In [ ]:
x=5.5
print("The Float Number is:",x)

The Float Number is: 5.5


In [ ]:
name = "ALi Kaiser , Trainer"
print("The name is :",name)

The name is : ALi Kaiser , Trainer


2. Basic Input and Output

In [ ]:
# Getting user input
name = input("Enter your name: ")
print("Hello", name)


Enter your name: a
Hello a


3. If-Else Conditions

In [ ]:
# If-Else example
age = int(input("Enter your age: "))

if age >= 18:
    print("You are an adult.")
else:
    print("You are a minor.")


Enter your age: 32
You are an adult.


**4. For Loop**

In [ ]:
# Print numbers 0 to 9
for i in range(10):
    print("Number:", i)


Number: 0
Number: 1
Number: 2
Number: 3
Number: 4
Number: 5
Number: 6
Number: 7
Number: 8
Number: 9


In [ ]:
# Print numbers 5 to 9
for i in range(5,10):
  print("Numers:",i)

Numers: 5
Numers: 6
Numers: 7
Numers: 8
Numers: 9


**5. While Loop**

In [ ]:
# Print numbers 0 to 4 using while
i = 0
while i < 5:
    print("Number:", i)
    i += 1


Number: 0
Number: 1
Number: 2
Number: 3
Number: 4


In [ ]:
i = 5
while i < 17:
    print("Number:", i)
    i += 3

Number: 5
Number: 8
Number: 11
Number: 14


**6. Lists**

In [ ]:
# List operations
fruits = ["apple", "banana", "cherry"]
print("All fruits:", fruits)

# Accessing elements
print("First fruit:", fruits[2])

# Adding elements
fruits.append("orange")
print("Updated fruits:", fruits)


All fruits: ['apple', 'banana', 'cherry']
First fruit: cherry
Updated fruits: ['apple', 'banana', 'cherry', 'orange']


**7. Functions**

In [ ]:
# Function to greet
def greet(name):
    print("Hello", name)

greet("ps")


Hello ps


**8. Loops with List**

In [ ]:
# Loop through a list
colors = ["red", "green", "blue"]
for color in colors:
    print("Color:", color)


Color: red
Color: green
Color: blue


**9. Dictionaries**

In [ ]:
# Dictionary example
student = {"name": "John", "age": 20, "grade": "A"}
print("Student grade:", student["grade"])


Student grade: A


**10. Basic Math Operations**

In [ ]:
a = 10
b = 3

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Modulus:", a % b)
print("Exponent:", a ** b)


Addition: 13
Subtraction: 7
Multiplication: 30
Division: 3.3333333333333335
Modulus: 1
Exponent: 1000


In [ ]:
x = int(input("Please enter an integer: "))

if x < 0:
    x = 0
    print('Negative changed to zero')
elif x == 0:
    print('Zero')
elif x == 1:
    print('Single')
else:
    print('More')

Please enter an integer: 1
Single


# **1. Introduction to Pandas**

In [ ]:
import pandas as pd
print("Pandas version:", pd.__version__)


Pandas version: 2.2.2


**2. Creating a DataFrame**

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie","Alice", "Bob", "Charlie","Alice", "Bob", "Charlie"],
    "Age": [25, 30, 25,25, 30, 35,25, 30, 35],
    "City": ["Dhaka", "Chittagong", "Rajshahi","Dhaka", "Chittagong", "Rajshahi","Dhaka", "Chittagong", "Rajshahi"]
}

df = pd.DataFrame(data)
print(df)


      Name  Age        City
0    Alice   25       Dhaka
1      Bob   30  Chittagong
2  Charlie   25    Rajshahi
3    Alice   25       Dhaka
4      Bob   30  Chittagong
5  Charlie   35    Rajshahi
6    Alice   25       Dhaka
7      Bob   30  Chittagong
8  Charlie   35    Rajshahi


**3. Reading Data from a CSV**

In [ ]:
# Create a dummy CSV file for demonstration
dummy_data = {
    "Col1": [1, 2, 3],
    "Col2": ["A", "B", "C"]
}
dummy_df = pd.DataFrame(dummy_data)
dummy_df.to_csv("dummy_data.csv", index=False)

# Now try reading the created dummy CSV file
try:
    df = pd.read_csv("dummy_data.csv")
    print(df.head())
except FileNotFoundError:
    print("The file 'dummy_data.csv' was not found.")

   Col1 Col2
0     1    A
1     2    B
2     3    C


**4. Basic DataFrame Operations**

In [ ]:
print(df.shape)       # Rows and columns
print(df.columns)     # Column names
print(df.dtypes)      # Data types
print(df.info())      # Summary
print(df.describe())  # Statistics


(3, 2)
Index(['Col1', 'Col2'], dtype='object')
Col1     int64
Col2    object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Col1    3 non-null      int64 
 1   Col2    3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes
None
       Col1
count   3.0
mean    2.0
std     1.0
min     1.0
25%     1.5
50%     2.0
75%     2.5
max     3.0


**5. Accessing Rows and Columns**

In [ ]:
print(df["Col1"])          # Access column
print(df[["Col1", "Col2"]])  # Multiple columns
print(df.loc[0])           # Access first row by label
print(df.iloc[0])          # Access first row by index

0    1
1    2
2    3
Name: Col1, dtype: int64
   Col1 Col2
0     1    A
1     2    B
2     3    C
Col1    1
Col2    A
Name: 0, dtype: object
Col1    1
Col2    A
Name: 0, dtype: object


**6. Filtering Rows**

In [ ]:
import pandas as pd

# Create a DataFrame with an 'Age' column
data_with_age = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["Dhaka", "Chittagong", "Rajshahi"]
}
df_with_age = pd.DataFrame(data_with_age)
df_with_age.head()

Name  Age        City
0    Alice   25       Dhaka
1      Bob   30  Chittagong
2  Charlie   35    Rajshahi

In [ ]:
import pandas as pd

# Create a DataFrame with an 'Age' column
data_with_age = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["Dhaka", "Chittagong", "Rajshahi"]
}
df_with_age = pd.DataFrame(data_with_age)

# Filter the DataFrame to get people older than 28
print(df_with_age[df_with_age["Age"] > 28])

      Name  Age        City
1      Bob   30  Chittagong
2  Charlie   35    Rajshahi


**7. Adding New Columns**

In [ ]:
df["New_Column"] = "Hello"
print(df)


   Col1 Col2 New_Column
0     1    A      Hello
1     2    B      Hello
2     3    C      Hello


**8. Modifying Data**

In [ ]:
df_with_age["Age"] = df_with_age["Age"] + 1
print(df_with_age)

      Name  Age        City
0    Alice   26       Dhaka
1      Bob   31  Chittagong
2  Charlie   36    Rajshahi


**9. Handling Missing Values**

In [ ]:
df = pd.DataFrame({
    "A": [1, 2, None],
    "B": [None, 5, 6]
})

print(df.isnull())          # Check missing
print(df.fillna(0))         # Replace missing with 0
print(df.dropna())          # Drop missing rows


       A      B
0  False   True
1  False  False
2   True  False
     A    B
0  1.0  0.0
1  2.0  5.0
2  0.0  6.0
     A    B
1  2.0  5.0


**10. Sorting Data**

In [ ]:
print(df_with_age.sort_values("Age"))         # Ascending
print(df_with_age.sort_values("Age", ascending=False))  # Descending

      Name  Age        City
0    Alice   26       Dhaka
1      Bob   31  Chittagong
2  Charlie   36    Rajshahi
      Name  Age        City
2  Charlie   36    Rajshahi
1      Bob   31  Chittagong
0    Alice   26       Dhaka


**11. Grouping Data**

In [ ]:
print(df_with_age.groupby("City")["Age"].mean())  # Average age by city

City
Chittagong    31.0
Dhaka         26.0
Rajshahi      36.0
Name: Age, dtype: float64


**12. Exporting to CSV**

In [ ]:
df.to_csv("output.csv", index=False)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
import pandas as pd
df1 = pd.read_csv('/content/drive/MyDrive/AI Training/Loan_Modelling.csv')

In [ ]:
print(df1.loc[1])           # Access first row by label

ID                        2.0
Age                      45.0
Experience               19.0
Income                   34.0
ZIPCode               90089.0
Family                    3.0
CCAvg                     1.5
Education                 1.0
Mortgage                  0.0
Personal_Loan             0.0
Securities_Account        1.0
CD_Account                0.0
Online                    0.0
CreditCard                0.0
Name: 1, dtype: float64


In [ ]:
print(df1.iloc[1])          # Access first row by index

ID                        2.0
Age                      45.0
Experience               19.0
Income                   34.0
ZIPCode               90089.0
Family                    3.0
CCAvg                     1.5
Education                 1.0
Mortgage                  0.0
Personal_Loan             0.0
Securities_Account        1.0
CD_Account                0.0
Online                    0.0
CreditCard                0.0
Name: 1, dtype: float64


In [ ]:
df1.head(9)

ID  Age  Experience  Income  ZIPCode  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49    91107       4    1.6          1         0   
1   2   45          19      34    90089       3    1.5          1         0   
2   3   39          15      11    94720       1    1.0          1         0   
3   4   35           9     100    94112       1    2.7          2         0   
4   5   35           8      45    91330       4    1.0          2         0   
5   6   37          13      29    92121       4    0.4          2       155   
6   7   53          27      72    91711       2    1.5          2         0   
7   8   50          24      22    93943       1    0.3          3         0   
8   9   35          10      81    90089       3    0.6          2       104   

   Personal_Loan  Securities_Account  CD_Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1  
5              0                   0           0       1           0  
6              0                   0           0       1           0  
7              0                   0           0       0           1  
8              0                   0           0       1           0

In [ ]:
# Filter the DataFrame to get people Income Greater than 99
print(df1[df1["Income"] > 207])

        ID  Age  Experience  Income  ZIPCode  Family  CCAvg  Education  \
3896  3897   48          24     224    93940       2   6.67          1   
4993  4994   45          21     218    91801       2   6.67          1   

      Mortgage  Personal_Loan  Securities_Account  CD_Account  Online  \
3896         0              0                   0           1       1   
4993         0              0                   0           0       1   

      CreditCard  
3896           1  
4993           0  


In [ ]:
print(df1["ZIPCode"])          # Access column

0       91107
1       90089
2       94720
3       94112
4       91330
        ...  
4995    92697
4996    92037
4997    93023
4998    90034
4999    92612
Name: ZIPCode, Length: 5000, dtype: int64


In [ ]:
print(df1[["Family", "Mortgage","ZIPCode"]])  # Multiple columns

      Family  Mortgage  ZIPCode
0          4         0    91107
1          3         0    90089
2          1         0    94720
3          1         0    94112
4          4         0    91330
...      ...       ...      ...
4995       1         0    92697
4996       4        85    92037
4997       2         0    93023
4998       3         0    90034
4999       3         0    92612

[5000 rows x 3 columns]


In [ ]:
df.tail(10)

A    B
0  1.0  NaN
1  2.0  5.0
2  NaN  6.0

In [ ]:
print(df.shape)       # Rows and columns
print(df.columns)     # Column names
print(df.dtypes)      # Data types
print(df.info())      # Summary
print(df.describe())  # Statistics

(3, 2)
Index(['A', 'B'], dtype='object')
A    float64
B    float64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       2 non-null      float64
 1   B       2 non-null      float64
dtypes: float64(2)
memory usage: 180.0 bytes
None
              A         B
count  2.000000  2.000000
mean   1.500000  5.500000
std    0.707107  0.707107
min    1.000000  5.000000
25%    1.250000  5.250000
50%    1.500000  5.500000
75%    1.750000  5.750000
max    2.000000  6.000000


In [ ]:
df2 = pd.read_excel('/content/drive/MyDrive/AI Training/MAT_216_S_04_ Spring 2025.xlsx')

In [ ]:
df2

Unnamed: 0     Unnamed: 1  \
0         NaN            NaN   
1         NaN            NaN   
2         NaN            NaN   
3         NaN    Course No :   
4         NaN  Course Title:   
5         NaN       Section:   
6         NaN  Faculty Name:   
7        SL #   STUDENT ID #   
8         NaN            NaN   
9           1       19101307   
10          2       21101289   
11          3       22101391   
12          4       22201238   
13          5       22201466   
14          6       22201734   
15          7       22221075   
16          8       22221124   
17          9       22241054   
18         10       22299173   
19         11       22299461   
20         12       22299530   
21         13       22301140   
22         14       22301375   
23         15       22301454   
24         16       22301511   
25         17       23101100   
26         18       23101159   
27         19       23101270   
28         20       23101342   
29         21       23101453   
30         22       23101460   
31         23       23101542   
32         24       23141010   
33         25       23201409   
34         26       23201426   
35         27       23201439   
36         28       23201555   
37         29       23221002   
38         30       23301103   
39         31       23301140   
40         32       23301228   
41         33       23301253   
42         34       23301255   
43         35       23301267   
44         36       23301307   
45         37       23301433   
46         38       23301653   
47         39       24101662   
48         40       24121044   
49         41       24241245   
50         42       24341262   

                                      BRAC UNIVERSITY Unnamed: 3 Unnamed: 4  \
0                                   Final Grade Sheet        NaN        NaN   
1                                         Spring 2025        NaN        NaN   
2   Department/ School: Mathematics and Natural Sc...        NaN        NaN   
3                                             MAT 216        NaN        NaN   
4          Linear Algebra and Fourier Transformation         NaN        NaN   
5                                                   4        NaN        NaN   
6                                     ALI KAISER(ALS)        NaN        NaN   
7                                        STUDENT NAME     ATTEN.       QUIZ   
8                                                 NaN       0.05        0.2   
9                                  NISHAT TASNIM NOVA          5      17.75   
10                                     ASIF AHMED JOY          5      15.25   
11                                       S. M. APURBO          5        8.5   
12                                 FAWZIA HASAN ORODI          5      18.25   
13                                  PURNIMA ROY TITHI          5      14.25   
14                              TANJUM RUKHSAT PRAPTY          5      15.25   
15                                    NIGAR ALAM RAFA          5      15.75   
16                                      FAHMIDA FAIZA          5      16.25   
17                                      MAHMUDUL AMIN          5      17.75   
18                                     ANIKA TABASSUM          5      16.25   
19                                     MASHRUR AREFIN          5      15.75   
20                                    MAHYBUL HUSSAIN          5       11.5   
21                                RUTBA TASNIM RIDIKA          5      15.75   
22                                       FAHIM SHIHAB          5      12.75   
23                               RAFIYAT REZA SHIRAJY          5      15.75   
24                        AL SHAHRIYAR RAHMAN PROTTOY          5      12.25   
25                                      ABRAR HOSSAIN          5      17.25   
26                                       ROWNAK JAHAN          5         16   
27                                        PARISA ASAF          5      16.75   
28                                KAMRUL HASSAN

In [ ]:
df5 = df2.tail(44)

In [ ]:
df5

Unnamed: 0    Unnamed: 1              BRAC UNIVERSITY Unnamed: 3  \
7        SL #  STUDENT ID #                 STUDENT NAME     ATTEN.   
8         NaN           NaN                          NaN       0.05   
9           1      19101307           NISHAT TASNIM NOVA          5   
10          2      21101289               ASIF AHMED JOY          5   
11          3      22101391                 S. M. APURBO          5   
12          4      22201238           FAWZIA HASAN ORODI          5   
13          5      22201466            PURNIMA ROY TITHI          5   
14          6      22201734        TANJUM RUKHSAT PRAPTY          5   
15          7      22221075              NIGAR ALAM RAFA          5   
16          8      22221124                FAHMIDA FAIZA          5   
17          9      22241054                MAHMUDUL AMIN          5   
18         10      22299173               ANIKA TABASSUM          5   
19         11      22299461               MASHRUR AREFIN          5   
20         12      22299530              MAHYBUL HUSSAIN          5   
21         13      22301140          RUTBA TASNIM RIDIKA          5   
22         14      22301375                 FAHIM SHIHAB          5   
23         15      22301454         RAFIYAT REZA SHIRAJY          5   
24         16      22301511  AL SHAHRIYAR RAHMAN PROTTOY          5   
25         17      23101100                ABRAR HOSSAIN          5   
26         18      23101159                 ROWNAK JAHAN          5   
27         19      23101270                  PARISA ASAF          5   
28         20      23101342          KAMRUL HASSAN NILOY          5   
29         21      23101453        SHAHADAT SIKDER FAHAD          5   
30         22      23101460                  SAZIA HASAN          5   
31         23      23101542          LOGNO RANJAN BARMAN          5   
32         24      23141010               TANVIR ISHTIAQ          5   
33         25      23201409        MOHAMMAD HASIBUL AMIN          5   
34         26      23201426            MRINMOY DAS ORGHO          5   
35         27      23201439                SAADMAN ZAHOR          5   
36         28      23201555          FUAD MOHAMMED JAWAD          5   
37         29      23221002                FARIHA RAHMAN          5   
38         30      23301103        SULTAN SAJED SHAHRIAR          5   
39         31      23301140                RAIYAN RAHMAN          5   
40         32      23301228               LABIBA TASHFIA          5   
41         33      23301253               MOHTASIM AHMED          5   
42         34      23301255            ATICK FUAD ANABIL          5   
43         35      23301267                 TASMIM RATRI          5   
44         36      23301307             SAMI BIN HEDAYET          5   
45         37      23301433        KAZI MD JAWADUL HOQUE          5   
46         38      23301653           ABDULLAH AL SHAFEE          5   
47         39      24101662               ROKEYA SUMAIYA          5   
48         40      24121044             SHAH ISRAR MIRZA          5   
49         41      24241245                 NABIL ISHMAM          5   
50         42      24341262       KHALED SAIFULLAH KARIM          5   

   Unnamed: 4  Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  \
7        QUIZ  ASSIGNMENT    MIDTERM      FINAL      Total      Total   
8         0.2         0.2       0.25        0.3        100          1   
9       17.75          20       24.5         13      80.25         80   
10      15.25          20         14       20.5      74.75         75   
11        8.5           0       13.5          5         32         32   
12      18.25          20       24.5         17      84.75         85   
13      14.25          20       10.5          0      49.75         50   
14      15.25          20          6        9.5      55.75         56   
15      15.75          20          9         15      64.75         65   
16      16.25          20        4.5       16.5      62.25         62   
17  

In [ ]:
df6 = pd.read_excel('/content/drive/MyDrive/AI Training/MAT_216_S_04_ Spring 2025.xlsx',sheet_name="Summary")

In [ ]:
df6

Unnamed: 0        BRAC UNIVERSITY            Unnamed: 2  \
0          NaN                    NaN                   NaN   
1          NaN     Summary of Results                   NaN   
2          NaN  Semester: Spring 2025                   NaN   
3          NaN                    NaN                   NaN   
4          NaN            Course No:                    NaN   
5          NaN          Course Title:                   NaN   
6          NaN           Section No:                    NaN   
7          NaN       Faculty Member:                    NaN   
8          NaN                    NaN                   NaN   
9          NaN                    NaN                   NaN   
10         NaN                    NaN                    A+   
11         NaN                    NaN                     A   
12         NaN                    NaN                    A-   
13         NaN                    NaN                    B+   
14         NaN                    NaN                     B   
15         NaN                    NaN                    B-   
16         NaN                    NaN                    C+   
17         NaN                    NaN                     C   
18         NaN                    NaN                    C-   
19         NaN                    NaN                    D+   
20         NaN                    NaN                     D   
21         NaN                    NaN                    D-   
22         NaN                    NaN                     F   
23         NaN                    NaN                Total    
24         NaN                    NaN                     P   
25         NaN                    NaN                     I   
26         NaN                    NaN                     W   
27         NaN                    NaN                   NaN   
28         NaN                    NaN                   NaN   
29         NaN                    NaN                   NaN   
30         NaN                    NaN  Examiner's Signature   

                                    Unnamed: 3  Unnamed: 4   Unnamed: 5  
0                                          NaN         NaN          NaN  
1                                          NaN         NaN          NaN  
2                                          NaN         NaN          NaN  
3                                          NaN         NaN          NaN  
4                                      MAT 216         NaN          NaN  
5   Linear Algebra and Fourier Transformation          NaN          NaN  
6                                            4         NaN          NaN  
7                              ALI KAISER(ALS)         NaN          NaN  
8                                          NaN         NaN          NaN  
9                              No. of Students         NaN  % of Total   
10                                           0         NaN            0  
11                                           3         NaN     7.142857  
12                                           8         NaN    19.047619  
13                                           6         NaN    14.285714  
14                                          10         NaN    23.809524  
15                                           2         NaN     4.761905  
16                                           3         NaN     7.142857  
17                                           2         NaN     4.761905  
18                                           2         NaN     4.761905  
19                                           1         NaN     2.380952  
20                                           2         NaN     4.761905  
21                                           1         NaN     2.380952  
22                                           2         NaN     4.761905  
23                                          42         NaN          100  
24                                         NaN         NaN          NaN  
25                                           0         NaN     

In [ ]:
df7 = pd.read_excel('/content/drive/MyDrive/AI Training/MAT_216_S_04_ Spring 2025.xlsx',sheet_name=1)

In [ ]:
df7

Empty DataFrame
Columns: []
Index: []

In [ ]:
print(df5.shape)       # Rows and columns
print(df5.columns)     # Column names
print(df5.dtypes)      # Data types
print(df5.info())      # Summary
print(df5.describe())  # Statistics

(44, 12)
Index(['Unnamed: 0', 'Unnamed: 1', 'BRAC UNIVERSITY', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11'],
      dtype='object')
Unnamed: 0         object
Unnamed: 1         object
BRAC UNIVERSITY    object
Unnamed: 3         object
Unnamed: 4         object
Unnamed: 5         object
Unnamed: 6         object
Unnamed: 7         object
Unnamed: 8         object
Unnamed: 9         object
Unnamed: 10        object
Unnamed: 11        object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 7 to 50
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Unnamed: 0       43 non-null     object
 1   Unnamed: 1       43 non-null     object
 2   BRAC UNIVERSITY  43 non-null     object
 3   Unnamed: 3       44 non-null     object
 4   Unnamed: 4       44 non-null     object
 5   Unnamed: 5       44 non

In [ ]:
df5.head(4)

Unnamed: 0    Unnamed: 1     BRAC UNIVERSITY Unnamed: 3 Unnamed: 4  \
7        SL #  STUDENT ID #        STUDENT NAME     ATTEN.       QUIZ   
8         NaN           NaN                 NaN       0.05        0.2   
9           1      19101307  NISHAT TASNIM NOVA          5      17.75   
10          2      21101289      ASIF AHMED JOY          5      15.25   

    Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9    Unnamed: 10  \
7   ASSIGNMENT    MIDTERM      FINAL      Total      Total         GRADES   
8          0.2       0.25        0.3        100          1  (with suffix)   
9           20       24.5         13      80.25         80             B+   
10          20         14       20.5      74.75         75              B   

   Unnamed: 11  
7       SUFFIX  
8   (in words)  
9         PLUS  
10       PLAIN

In [ ]:
df3=pd.read_excel('/content/drive/MyDrive/AI Training/Training Grades.xlsx',sheet_name=2)

In [ ]:
df3

ID  Grade 
0  11      55
1  12      66
2  13      77
3  14      88
4  15      99

1. Introduction to NumPy
What is NumPy?

NumPy (Numerical Python) is a library for numerical computations in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

Core Data Structure: The primary data structure in NumPy is the ndarray (N-dimensional array).

Why Use NumPy?

Fast and efficient operations on large datasets.

Provides vectorized operations, which are much faster than regular Python lists.

Integrated with other scientific libraries like SciPy, Pandas, and Matplotlib.

2. NumPy Array Basics
Creating NumPy Arrays

Using np.array(): Create a NumPy array from a list or a tuple.

python
Copy


In [ ]:
import numpy as np
arr = np.array([1.1, 2.3, 3.5, 4.4, 6.5])  # 1D array
print(arr)


[1.1 2.3 3.5 4.4 6.5]


In [ ]:
print(arr[4])

6.5


In [ ]:
print(arr[2:4])

[3.5 4.4]


In [ ]:
print(arr[1:4])

[2.3 3.5 4.4]


In [ ]:
print(arr[0])  # Access the first element

1.1


In [ ]:
print(arr[3])  # Access the first element

4.4


Array Dimensions

1D Array: A single row or column of data.

2D Array: A matrix (rows and columns).

3D Array: A collection of matrices, like a tensor.

python
Copy


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(arr_2d[0, 2])  # Access element in 2D array (row 0, column 1)

3


Array Shape

.shape tells the shape of an array (number of rows, columns, etc.).




In [ ]:
print(arr.shape)  # Output: (5,)
print(arr_2d.shape)  # Output: (2, 3)


(5,)
(2, 3)


Array Data Type:

.dtype tells the data type of the elements in the array.

python
Copy


In [ ]:
print(arr.dtype)


float64


In [ ]:
print(arr_2d.dtype)

int64


3. NumPy Array Indexing and Slicing
Indexing

Access individual elements using indices.

In [ ]:
print(arr[0])  # Access the first element
print(arr_2d[0, 1])  # Access element in 2D array (row 0, column 1)


1.1
2


Slicing

Extract subsets of arrays using slicing.




In [ ]:
print(arr)

[1.1 2.3 3.5 4.4 6.5]


In [ ]:
print(arr[1:4])  # Slice from index 1 to 3

[2.3 3.5 4.4]


In [ ]:
print(arr[1:4])  # Slice from index 1 to 3
print(arr_2d[0, :])  # Slice the first row


[2.3 3.5 4.4]
[1 2 3]


Advanced Indexing

Use boolean indexing and fancy indexing to extract elements based on conditions or indices.

In [ ]:
print(arr[arr > 2])  # Elements greater than 2
print(arr_2d[[0, 1], 2])  # Specific rows and columns


[2.3 3.5 4.4 6.5]
[3 6]


4. Array Operations
Mathematical Operations

NumPy allows element-wise mathematical operations on arrays, such as addition, multiplication, etc.

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [ ]:
print(arr - 5)  # Sutract 5 to each element

[-4 -3 -2 -1]


In [ ]:
print(arr/ 2)  # Divide each element by 2

[0.5 1.  1.5 2. ]


In [ ]:
print(arr * 7)  # Multiply each element by 2

[ 7 14 21 28]


In [ ]:
arr1 = (arr + 5)  # Add 5 to each element

In [ ]:
print(arr1)

[6 7 8 9]


In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr + 5)  # Add 5 to each element
print(arr * 2)  # Multiply each element by 2


[6 7 8 9]
[2 4 6 8]


Array Broadcasting

Broadcasting allows NumPy to perform operations on arrays of different shapes in a way that makes sense.

In [ ]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [ ]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])
print(arr_2d)

[[10 20 30]
 [40 50 60]]


In [ ]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])
print(arr_2d + arr)  # Broadcasting addition


[[11 22 33]
 [41 52 63]]


5. Reshaping and Modifying Arrays
Reshaping Arrays

Use .reshape() to change the shape of the array.



In [ ]:

arr = np.array([1, 2, 3, 4, 5, 6])
arr_reshaped = arr.reshape(2, 3)  # 2 rows, 3 columns
print(arr_reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr_reshaped = arr.reshape(3, 2)  # 2 rows, 3 columns
print(arr_reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr_reshaped1 = arr.reshape(2, 3)  # 2 rows, 3 columns
print(arr_reshaped1)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr_reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr_flatten=arr_reshaped.flatten()

In [ ]:
print(arr_flatten)

[1 2 3 4 5 6]


Flattening Arrays

Convert a multi-dimensional array into a 1D array.




In [ ]:
arr_flat = arr_reshaped.flatten()


6. NumPy Array Operations for Statistical Analysis
Basic Statistics

NumPy provides a variety of functions for calculating statistics on arrays.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
print(np.sum(arr))  # Sum of values

21


In [ ]:
print(np.max(arr))  # Maximum value

6


In [ ]:
print(np.min(arr))  # Minimum value

1


In [ ]:
print(np.median(arr))  # Median of the array

3.5


In [ ]:
print(np.mean(arr))  # Mean of the array

3.5


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # Mean of the array
print(np.median(arr))  # Median of the array
print(np.std(arr))  # Standard deviation of the array


3.0
3.0
1.4142135623730951


Min, Max, and Sum

np.min(), np.max(), and np.sum() to get the minimum, maximum, and sum of the array elements.




In [ ]:
print(np.min(arr))  # Minimum value
print(np.max(arr))  # Maximum value
print(np.sum(arr))  # Sum of values


1
5
15


. Random Numbers and Seed Generation
Random Number Generation

Use np.random for generating random numbers, such as random integers, floats, or distributions.

In [ ]:
rand_int = np.random.randint(0, 10, size=5)  # Random integers
rand_float = np.random.rand(3, 3)  # Random floats between 0 and 1


In [ ]:
rand_int = np.random.randint(0, 10, size=5)  # Random integers
print(rand_int)

[6 4 4 0 4]


In [ ]:
#Random 20 integers etween 10 to 100
rand_int = np.random.randint(10, 100, size=20)  # Random integers
print(rand_int)

[44 42 81 18 10 58 26 79 59 54 97 75 88 88 28 95 91 62 14 53]


9. Working with Multi-dimensional Arrays
Creating Multi-dimensional Arrays

Use np.array() or np.zeros(), np.ones() for creating multi-dimensional arrays.

In [ ]:
arr_3d = np.zeros((3, 3, 3))  # 3x3x3 array filled with zeros


In [ ]:
print(arr_3d)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


Accessing Multi-dimensional Arrays

Use advanced indexing to access elements.

In [ ]:
print(arr_3d[0, 1, 2])  # Access element at position (0,1,2)


0.0


10. Linear Algebra in NumPy
Dot Product

Compute the dot product of two arrays.

In [ ]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print(np.dot(arr1, arr2))  # Dot product


11


In [ ]:
print(np.dot(arr1,arr2))

11


In [ ]:
print(arr1)

[1 2]


In [ ]:
print(arr2)

[3 4]


Matrix Multiplication

Use np.matmul() or @ operator for matrix multiplication.




In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(np.matmul(matrix1, matrix2))  # Matrix multiplication


[[19 22]
 [43 50]]


In [ ]:
np.matmul(matrix1,matrix2)

array([[19, 22],
       [43, 50]])

In [ ]:
print(matrix2)

[[5 6]
 [7 8]]


In [ ]:
print(matrix1)

[[1 2]
 [3 4]]


Object Oriented Programming.

📚 Module 1: Getting Started with Python
✅ Lesson 1.1: Hello World

In [ ]:
# Run this in Google Colab
print("Hello, world!")


Hello, world!


🔑 Concepts:

What is Python?

Code runs top to bottom.

print() displays output.



📚 Module 2: Python Basics
✅ Lesson 2.1: Variables and Data Types

In [ ]:
name = "Alice"
age = 25
is_student = True

print(name, age, is_student)


Alice 25 True


🧠 Concepts:

Strings, integers, booleans

Variables store information

✅ Lesson 2.2: Functions

In [ ]:
def greet(name):
    print("Hello", name)

greet("Audience")


Hello Audience


In [ ]:
def add_numbers(c,d):
    return(c+d)
result1 = add_numbers(1000,200)
print(result1)

1200


In [ ]:
def multipy_numbers(c,d):
    return(c*d)
result2= multipy_numbers(2,20)
print(result2)

40


In [ ]:
def divide_numbers(c,d):
    return(c/d)
result3= divide_numbers(200,20)
print(result3)

10.0


🧠 Concepts:

def defines a function

Functions can take input and do something

📚 Module 3: Introduction to Classes and OOP
✅ Lesson 3.1: Creating a Class

In [ ]:
#Createing Master Class / Master Copy
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def greet(self):
        print("Hi, I'm", self.name, "and I'm", self.age, "years old.")

# Create an object
person1 = Person("Alice", 25)
person2 = Person("Kaiser",35)
person3 = Person("Masum",15)
person4 = Person("Arif",55)
person5 = Person("Yasmin",75)
person1.greet()
person2.greet()
person3.greet()
person4.greet()
person5.greet()


Hi, I'm Alice and I'm 25 years old.
Hi, I'm Kaiser and I'm 35 years old.
Hi, I'm Masum and I'm 15 years old.
Hi, I'm Arif and I'm 55 years old.
Hi, I'm Yasmin and I'm 75 years old.


🧠 Concepts:

class defines a blueprint

__init__ is a special method (constructor)

self refers to the object

Creating an object: person1 = Person(...)

✅ Lesson 3.2: Inheritance


In [ ]:
class Student(Person):
    def __init__(self, name, age, student_id):
        super().__init__(name, age)
        self.student_id = student_id

    def show_id(self):
        print("My student ID is", self.student_id)

# Create a student
s1 = Student("Bob", 20, "S123")
s1.greet()
s1.show_id()

s2 =Student("Keya",22, "S142")
s2.greet()
s2.show_id()

s3 = Student("M", 22, 's23')
s3.greet()
s3.show_id()


Hi, I'm Bob and I'm 20 years old.
My student ID is S123
Hi, I'm Keya and I'm 22 years old.
My student ID is S142
Hi, I'm M and I'm 22 years old.
My student ID is s23


🧠 Concepts:

Inheritance: Student extends Person

super() calls parent methods

📚 Module 4: Applying OOP to a Simple AI Task
✅ Lesson 4.1: AI-Inspired Class — Simple Chatbot

In [ ]:
class ChatBot:
    def __init__(self, name):
        self.name = name

    def respond(self, message):
        if "hello" in message.lower():
            return f"{self.name}: Hello! How can I help you?"
        elif "bye" in message.lower():
            return f"{self.name}: Goodbye!"
        else:
            return f"{self.name}: Sorry, I don't understand."

# Using the ChatBot
bot = ChatBot("AI-Bot")
print(bot.respond("Hello there"))
print(bot.respond("What's up?"))
print(bot.respond("bye"))


AI-Bot: Hello! How can I help you?
AI-Bot: Sorry, I don't understand.
AI-Bot: Goodbye!


🧠 Concepts:

OOP applied to AI logic

Encapsulation of behavior (respond)

📚 Module 5: OOP for ML (With Real Data and Models)
We'll use sklearn, pandas, and matplotlib (already available in Google Colab).

✅ Lesson 5.1: Class-Based ML with Scikit-Learn
🔍 Goal: Teach how to structure an ML model using a Python class.

🚀 Step-by-step Explanation
Load and preprocess data

Create a class MLModel

Define methods:

load_data()

train_model()

evaluate_model()

Use the class to run ML



In [ ]:
# Import libraries
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Define class
class MLModel:
    def __init__(self):
        self.model = LogisticRegression()
        self.X_train = None
        self.X_test = None
        self.y_train = None
        self.y_test = None

    def load_data(self):
        data = load_iris()
        X = pd.DataFrame(data.data, columns=data.feature_names)
        y = pd.Series(data.target)
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X, y, test_size=0.3, random_state=42)
        print("✅ Data loaded and split")

    def train_model(self):
        self.model.fit(self.X_train, self.y_train)
        print("✅ Model trained")

    def evaluate_model(self):
        predictions = self.model.predict(self.X_test)
        accuracy = accuracy_score(self.y_test, predictions)
        print(f"📊 Model accuracy: {accuracy * 100:.2f}%")

# Run everything
ml = MLModel()
ml.load_data()
ml.train_model()
ml.evaluate_model()


✅ Data loaded and split
✅ Model trained
📊 Model accuracy: 100.00%


🧠 Concepts Students Learn:
How to structure code with OOP

Data loading and splitting

Training and evaluating a model

Encapsulation in AI systems

